[package]
name = "cpoc_revision"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.2"
rand = "0.8.5"
sha2 = "0.10.6"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "nfp_bench"
harness = false